# This file will be loaded by default
mission_file_name: "mission_depth_only.xml"
#mission_file_name: "mission_empty.xml"

physics:
  rho: 1020.0
  g: 9.81

  # Float
  m: 13.5
  diam_collerette: 0.35
  screw_thread: 8.11e-5
  tick_per_turn: 1
  piston_diameter: 0.0195
  piston_max_value: 2460.0
  piston_speed_max_tick: 20
  piston_ref_eq: 2000

driver:
  power:
    frequency: 0.2

  piston:
    frequency: 20.0
    divider_frequency: 10 # frequency of published message = frequency/divider_frequency
    distance_fast_move: 100
    # If speed_fast_move is too high, disturbances are create on I2C external pressure sensor
    speed_fast_move_factor: 2.0
    speed_reset: 25
    speed_out_min: 25
    speed_in_min: 25
    speed_out_slope: 0.5
    speed_in_slope: 0.5
    speed_depth_layer: 5.0
    depth_max: 500.0
    depth_big_piston: 2.0
    tick_big_piston: 300
    speed_max: 50
    reached_switch_off: True
    error_interval: 6
    # below max values used to filter wrong pic i2c readings
    tick_max: 3000
    piston_velocity_max: 100.

  pressure_ext:
    frequency: 5

  pressure_int:
    frequency: 5
    # primary i2c address = 0x76, secondary = 0x77
    primary_i2c_address: True

  temperature_ext:
    frequency: 5

filter:
  depth_filter:
    frequency: 25 # Frequency of the spinOnce, reduce latency with new pressure message
    filter_window_size: 6
    filter_mean_half_width: 2
    filter_mean_width_velocity: 6
    velocity_dt_sample: 5
    filter_velocity_mean_half_width: 2
    velocity_limit: 0.5
    zero_depth_pressure: 1.024 # Initial zero depth value
    zero_depth_window_size: 100 # Number of sample to be averaged to get zero depth (see time_delay_zero_depth_condition)

  temperature_filter:
    frequency: 5
    filter_median_size: 6
    filter_mean_width: 2
    filter_mean_width_velocity: 5
    velocity_delta_size: 5
    velocity_limit: 2.0

  batteries_filter:
    frequency: 0.2
    filter_median_size: 6
    filter_mean_width: 2

  internal_sensor_filter:
    frequency: 5
    filter_median_size: 6
    filter_mean_width: 2

  lambert:
    frequency: 5
    nb_sample_mean: 6
    nb_sample_between_heading: 150

iridium:
  duration_between_msg: 60
  wait_time_surface: 10
  depth_surface_limit: 0.5
  debug: False
  enable_gnss_iridium: False
  version: 1

kalman:
  frequency: 25.0
  # !! will have to be increased latter on !!
  # need to be shallower than depth regulation parameter
  enable_depth: 0.1

  # turned on
  estimated_first_error_equilibrium_tick: 619

  gamma_alpha_velocity: 1.0e-3 # Error of model
  gamma_alpha_depth: 1.0e-5 # Error of model
  gamma_alpha_offset: 20.0e0 # in ticks
  gamma_alpha_chi: 1.0e-3 # in ticks
  gamma_alpha_chi2: 1.0e-5 # in ticks
  gamma_alpha_cz: 1.0e-4

  gamma_init_velocity: 1.0e-1
  gamma_init_depth: 1.0e-2
  gamma_init_offset: 500.0 # in ticks
  gamma_init_chi: 1.0 # in ticks
  gamma_init_chi2: 1.0e-2 # in ticks
  gamma_init_cz: 0.1

  gamma_beta_depth: 0.05

  init_chi: -1.0
  init_chi2: 0.0

mission:
  frequency: 1.0
  flash_time_next_waypoint: 3
  limit_velocity_default: 0.02
  approach_velocity_default: 1.0

regulation:
  depth_controller:
    frequency: 25.0
    divider_frequency: 25
    root_regulation: -0.15
    # !!
    limit_depth_controller: 0.2

    delta_velocity_lb: -0.01
    delta_velocity_ub:  0.01

    delta_position_lb: -1.
    delta_position_ub:  1.

    hysteresis_piston: 0.6
    speed_volume_sink: 10.0

    hold_depth_enable: False
    hold_depth_value_enter: 0.30
    hold_depth_value_exit: 0.30
    hold_velocity_enter: 0.01

    safety_no_data: 10.0

    no_motions_enable: True
    no_motions_period_long: 300.0
    no_motions_period_short: 60.0

  waypoint:
    frequency: 10.0
    delta_valid_time: 3.0

    hysteresis_circle_in: 2.0
    hysteresis_circle_out: 4.0

    coeff_P: 0.8
    coeff_D: 0.2
    linear_speed: 1.3
    depth_limit_switch_off: 0.5
    max_angular_velocity: 1.0

safety:
  frequency: 1.0

  # Leak detection
  safety_depressure: True
  humidity_limit: 70.0

  # !! AP turned off for bench tests
  internal_pressure_detection: True
  delta_volume_allowed: 1.0
  delta_ref_allowed: 10.0
  volume_ref: 0.006
  transition_tick_law: 650.0
  pressure_internal_max: 850.0

  # Zero depth reset
  max_depth_reset_zero: 1.0
  max_speed_reset_zero: 0.1
  limit_piston_position_reset_depth: 3
  time_delay_zero_depth_condition: 20

  # Depth limit
  safety_pressure_limit: True
  pressure_limit: 50.
  time_before_pressure_emergency: 3.0

  # Seafloor
  seafloor_detection: True
  time_before_seafloor_emergency: 20.0

  # Batteries
  safety_battery: True
  # !! was 11
  battery_limit: 12.0

  # Flash
  enable_flash: True
  limit_depth_flash_enable: 0.5

  # Message delay
  time_delay_batteries_msg: 60.0
  time_delay_internal_sensor_msg: 60.0
  time_delay_external_sensor_msg: 60.0
  time_delay_depth_msg: 60.0
  time_delay_piston_state_msg: 60.0
  time_delay_euler_msg: 1.0
