mission_file_name: "mission_depth_only.xml"

physics:
  # Float
  m: 18.0
  piston_ref_eq: 2100

driver:
  thruster:
    thruster_left_pin: 0
    thruster_right_pin: 1
    invert_left: false
    invert_right: true

  imu:
    ellipsoid_offset: [0, 0, 0]
    ellipsoid_matrix0: [1, 0, 0]
    ellipsoid_matrix1: [0, 1, 0]
    ellipsoid_matrix2: [0, 0, 1]

    accel_min: [-9.61750807,  -9.97663832, -10.20648168]
    accel_max: [10.20169327,   9.88087025,   9.74918916]

    gyro_bias: [-0.00013038, 0.00055432,  -0.00025377]